baseURL = "https://devopsnewsletters.com"
title = "DevOps Newsletters"
theme = "coder"
languagecode = "en"

[params]
    author = "DevOps Newsletters"
    description = "Continuous learning is a critical part of DevOps. Staying current is imperative. These are DevOps newsletters of note from several well regarded DevOps leaders."
    keywords = "devops,cloud native,open source,newsletters"
    info = "DevOps Newsletters of Note"

    hideCredits = true
    hideCopyright = true

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/chris-short/devopsnewsletters.com"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/ChrisShort"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://linkedin.com/in/thechrisshort/"

[[params.sites]]
    name = "Devops Weekly"
    description = "A weekly slice of devops news brought to you by Gareth Rushgrove."
    weight = 1
    url = "https://www.devopsweekly.com/"
[[params.sites]]
    name = "DevOps'ish"
    description = "DevOps, Cloud Native, Open Source, and the 'ish in between."
    weight = 2
    url = "https://devopsish.com/"
[[params.sites]]
    name = "Last Week in AWS"
    description = "A weekly roundup of news from Amazon's cloud ecosystem — sprinkled with snark."
    weight = 3
    url = "https://lastweekinaws.com/"
[[params.sites]]
    name = "Kube Weekly"
    description = "Aggregating all interesting weekly news about Kubernetes in the form of a newsletter."
    weight = 4
    url = "http://kube.news/"
[[params.sites]]
    name = "The New Stack"
    description = "A digest of the week's most important stories & analyses about the services and infrastructures that developers build and the cultural impact that has on the way we work and live."
    weight = 5
    url = "https://thenewstack.io/newsletter-archive"
[[params.sites]]
    name = "DevOps Dispatch"
    description = "The DevOps Dispatch is a weekly curated publication full of articles and podcast episodes related to DevOps."
    weight = 6
    url = "https://devopsdispatch.com/"
[[params.sites]]
    name = "SRE Weekly"
    description = "A newsletter devoted to everything related to keeping a site or service available as consistently as possible."
    weight = 7
    url = "https://sreweekly.com/"
[[params.sites]]
    name = "appops reloaded"
    description = "Keep up to date with all things containers, Kubernetes, Docker, Go, Linux, devops, cloud native apps, CI/CD, microservices, AWS, Azure, GCP."
    weight = 8
    url = "https://tinyletter.com/mhausenblas"
[[params.sites]]
    name = "Security Newsletter"
    description = "Last week's news on infosecurity, digested to an easy format."
    weight = 10
    url = "https://securitynewsletter.co/"
[[params.sites]]
    name = "Monitoring Weekly"
    description = "Curated monitoring articles to your inbox each week."
    weight = 11
    url = "https://weekly.monitoring.love/"
[[params.sites]]
    name = "Infrastructure as a Newsletter"
    description = "Get Digital Ocean's roundup of sysadmin tutorials and open source happenings delivered to your inbox once you sign up and again every two weeks."
    weight = 12
    url = "https://www.digitalocean.com/community/newsletter"
[[params.sites]]
    name = "Opensource.com Highlights"
    description = "Opensource.com is about sharing how the open source way can change our world in the same way the open source model has changed software."
    weight = 13
    url = "https://opensource.com/"
[[params.sites]]
    name = "O'Reilly Systems Engineering and Operations Newsletter"
    description = "Stay informed. Receive weekly insight from industry insiders—plus exclusive content, offers, and more on the topic of systems engineering and operations."
    weight = 14
    url = "https://www.oreilly.com/webops-perf/newsletter.html"
[[params.sites]]
    name = "WebOps Weekly"
    description = "A weekly newsletter on Web operations, infrastructure, performance, the backend, and tooling, from the browser down to the metal."
    weight = 100
    url = "https://webopsweekly.com/"